// youmenosay CF 設定ファイル v1.3
// 管理画面(admin.html)から編集・エクスポートできます

window.YMS_CONFIG = {
  version: '1.3.0',

  soreosUrl: 'https://soreosu.com/projects/youmenosay',

  heroImageFile: 'hero-main.jpg',

  currentAmount: 0,
  currentAmountUpdatedAt: '',

  // ヒーロータイポグラフィ
  heroTypography: {
    titleSize:   '4rem',
    leadSize:    '1.1rem',
  },

  // テーマ設定（メインビジュアルから抽出した配色）
  theme: {
    colorPrimary:   '#ff5dae',   // ビビッドピンク（メインビジュアルのキーカラー）
    colorSecondary: '#c840f0',   // マゼンタパープル（衣装カラー）
    colorAccent:    '#ffcc00',   // ゴールド（メインビジュアルの星）
    colorBg:        '#160828',   // ウォームダークパープル（夜空）
    colorSurface:   '#231040',   // ダークパープル（カード背景）
    colorBorder:    '#3e1a58',   // パープルボーダー
    colorText:      '#fff3ff',   // ウォームホワイト
    colorTextMuted: '#cc90c0',   // ミュートピンク
    fontHeading:    "'Zen Maru Gothic', sans-serif",
    fontBody:       "'Noto Sans JP', sans-serif",
  },

  // 編集可能テキスト（空文字はHTMLデフォルト表示）
  // **文字** でハイライト（太字）表示
  content: {
    heroTitle:       '',
    heroLead:        '',
    goalAmount:      '5,000,000',
    aboutMain:       '',
    projectMain:     '',
    producerMessage: '',
  },

  // スケジュール（管理画面から追加・編集・削除可）
  schedule: [
    {
      id: 's1',
      date: '2025-05-08',
      dateLabel: '5月8日(木)',
      title: 'クラウドファンディング スタート',
      description: 'スタートダッシュプラン公開開始',
      highlight: false,
    },
    {
      id: 's2',
      date: '2025-05-11',
      dateLabel: '5月11日(日)',
      title: 'スタートダッシュプラン 終了 / 在宅プラン等 順次公開開始',
      description: '23:59まで（コンビニ払い期限：5月16日(金) 23:59）',
      highlight: false,
    },
    {
      id: 's_sale1',
      date: '2025-05-25',
      dateLabel: '5月25日(月)',
      title: '在宅プラン・法人プラン・体験型プラン（一部）販売開始',
      description: '在宅プラン全4種 / 法人プラン全3種 / アフタヌーンティー女子会・男子会 / 撮影会（各メンバー5種）21時〜',
      highlight: false,
    },
    {
      id: 's_sale2',
      date: '2025-05-27',
      dateLabel: '5月27日(水)',
      title: 'クリエイティブプラン 販売開始',
      description: '全6種（自己紹介ソング・楽曲制作・デザイン・小物制作・動画制作・YouTuber）21時〜',
      highlight: false,
    },
    {
      id: 's_sale3',
      date: '2025-06-01',
      dateLabel: '6月1日(月)',
      title: 'オフイベ参加権 販売開始',
      description: 'きゃのち・さりちゃん・れーにゃ・ねむちゃん・ぺんざむ（各15人限定）21時〜',
      highlight: false,
    },
    {
      id: 's_sale4',
      date: '2025-06-10',
      dateLabel: '6月10日(水)',
      title: 'スペシャルプラン 販売開始',
      description: 'ゆめのせいサポートメンバープラン（1枠限定）21時〜',
      highlight: false,
    },
    {
      id: 's3',
      date: '2025-07-11',
      dateLabel: '7月11日(土)',
      title: 'きゃのちと！オフイベ / ねむちゃんと！オフイベ',
      description: '15:00〜 / 11:00〜（各2時間・都内近郊）',
      highlight: false,
    },
    {
      id: 's4',
      date: '2025-07-12',
      dateLabel: '7月12日(日)',
      title: 'さりちゃんと！オフイベ / れーにゃと！オフイベ / ぺんざむと！オフイベ',
      description: '15:00〜 / 19:00〜 / 11:00〜（各2時間・都内近郊）',
      highlight: false,
    },
    {
      id: 's5',
      date: '2025-08-09',
      dateLabel: '8月9日(日)',
      title: 'アフタヌーンティー女子会・男子会',
      description: '12:00〜（女子）/ 14:00〜（男子）各70分間',
      highlight: false,
    },
    {
      id: 's6',
      date: '2025-09-13',
      dateLabel: '9月13日(日)',
      title: 'はじめての！撮影会',
      description: '午後〜（都内スタジオ）',
      highlight: false,
    },
    {
      id: 's7',
      date: '2027-03-01',
      dateLabel: '2027年',
      title: 'youmenosay 5周年',
      description: 'アニメーションMV完成・試写会開催（目標達成時）',
      highlight: true,
    },
  ],

  // リターンデータ（管理画面から追加・編集・削除可）
  rewardsData: [
    {
      id: 'startdash',
      tabLabel: 'スタートダッシュ',
      headerType: 'expired',
      title: 'スタートダッシュプラン',
      periodText: '5月8日(木) 〜 5月11日(日) 23:59まで',
      periodNote: '※コンビニ支払いの場合、支払い期限は5月16日(金) 23:59まで',
      visible: true,
      comingSoon: false,
      notices: [],
      cards: [
        {
          id: 'startdash_1000',
          price: '1,000',
          limit: '',
          title: 'スタートダッシュプラン ☆1,000円',
          description: '',
          subItems: [],
          items: ['4周年ワンマンライブ直後のオフショット動画'],
          delivery: ['動画はご登録のメールアドレスへお届けします'],
        },
        {
          id: 'startdash_3000',
          price: '3,000',
          limit: '',
          title: 'スタートダッシュプラン ☆3,000円',
          description: '',
          subItems: [],
          items: ['4周年ワンマンライブ直後のオフショット動画', '宛名&サイン入りチェキ（メンバー選択可）'],
          delivery: ['動画はご登録のメールアドレスへお届けします', 'チェキはご登録の住所へお届けします', 'メンバー選択：北郷可恩 / 雪乃さり / 雨宮れいな / ねむいのはる / 陽葵優叶', 'チェキへの宛名は購入時アンケートにご記入ください'],
        },
      ],
    },
    {
      id: 'zaitaku',
      tabLabel: '在宅プラン',
      headerType: 'normal',
      title: '在宅プラン',
      periodText: '',
      periodNote: '',
      visible: true,
      comingSoon: false,
      notices: [],
      cards: [
        {
          id: 'zaitaku_3000',
          price: '3,000',
          limit: '',
          image: 'zaitaku-3000.jpg',
          title: '在宅プラン ¥3,000',
          description: '',
          subItems: [],
          items: ['お礼メッセージ動画', 'エンドロールへのお名前掲載'],
          delivery: ['動画はご登録のメールアドレスへお届けします', 'アニメーションMV完成時のエンドロールにお名前を掲載します', 'エンドロール掲載名は購入時アンケートにご記入ください'],
        },
        {
          id: 'zaitaku_5000',
          price: '5,000',
          limit: '',
          image: 'zaitaku-5000.jpg',
          title: '在宅プラン ¥5,000',
          description: '',
          subItems: [],
          items: ['お礼メッセージ動画', 'エンドロールへのお名前掲載', '実写ミニのぼり（お宛名入り・メンバー選択可）'],
          delivery: ['動画はご登録のメールアドレスへお届けします', 'ミニのぼりはご登録の住所へお届けします', 'メンバー選択：北郷可恩 / 雪乃さり / 雨宮れいな / ねむいのはる / 陽葵優叶', 'のぼり宛名・エンドロール掲載名は購入時アンケートにご記入ください', '※ 複数メンバー購入希望の場合は、メンバーごとに数量1で個別にご購入ください'],
        },
        {
          id: 'zaitaku_10000',
          price: '10,000',
          limit: '',
          image: 'zaitaku-10000.jpg',
          title: '在宅プラン ¥10,000',
          description: '',
          subItems: [],
          items: ['お礼メッセージ動画', 'エンドロールへのお名前掲載', '実写ミニのぼり（お宛名入り・メンバー選択可）', '実写集合アクスタ'],
          delivery: ['動画はご登録のメールアドレスへお届けします', 'ミニのぼり・アクスタはご登録の住所へお届けします', 'のぼりメンバー選択：北郷可恩 / 雪乃さり / 雨宮れいな / ねむいのはる / 陽葵優叶', 'のぼり宛名・エンドロール掲載名は購入時アンケートにご記入ください'],
        },
        {
          id: 'zaitaku_30000',
          price: '30,000',
          limit: '',
          image: 'zaitaku-30000.jpg',
          title: '在宅プラン ¥30,000',
          description: '',
          subItems: [],
          items: ['お礼メッセージ動画', 'エンドロールへのお名前掲載', '実写ミニのぼり（お宛名入り・メンバー選択可）', '実写集合アクスタ', '実写フルグラフィックTシャツ（メンバー選択可）', 'オンラインおはなし会参加券（5分間・メンバー選択可）'],
          delivery: ['動画はご登録のメールアドレスへお届けします', 'グッズ類はご登録の住所へお届けします', 'メンバー選択（のぼり・Tシャツ・おはなし会）：北郷可恩 / 雪乃さり / 雨宮れいな / ねむいのはる / 陽葵優叶', 'おはなし会はZoomにて実施。ヒアリングフォームで日程調整します', '※ Tシャツのサイズ展開は確認中です', '※ 複数メンバー購入希望の場合は、メンバーごとに数量1で個別にご購入ください'],
        },
      ],
    },
    {
      id: 'taiken',
      tabLabel: '体験型プラン',
      headerType: 'normal',
      title: '体験型プラン',
      periodText: '',
      periodNote: '',
      visible: true,
      comingSoon: false,
      notices: [
        '本プランは「ファン交流イベント（体験型興行）」であり、特定の支援者様への個別奉仕（接待）を目的としたものではありません。',
        '購入後のキャンセルは不可となります。',
        '安全管理：常にスタッフが同行し、グループ行動を徹底します。特定のメンバーとの1対1の状況は行えません。',
        '本人確認：当日は公的な身分証明書による本人確認を行います。',
        '規約遵守：身体接触、プライベートな質問、連絡先の交換等は一切禁止です。',
      ],
      cards: [
        {
          id: 'taiken_women30',
          price: '30,000',
          limit: '15人限定',
          image: 'taiken-tea-women.jpg',
          title: '女子限定！アフタヌーンティー女子会',
          description: '5/25(月) 21時〜販売開始',
          subItems: [],
          items: ['アフタヌーンティー女子会参加権', '開催：8月9日(日) 12時〜（70分間）', '場所：都内近郊予定', '集合チェキ（サインなし）込み・食事代込み'],
          delivery: ['※ 女性の方限定のプランです', '※ 当日は性別が確認できる身分証明書をご持参ください', '※ 会場までの交通費はご負担いただきます'],
        },
        {
          id: 'taiken_men30',
          price: '30,000',
          limit: '15人限定',
          image: 'taiken-tea-men.jpg',
          title: '男子限定！アフタヌーンティー男子会',
          description: '5/25(月) 21時〜販売開始',
          subItems: [],
          items: ['アフタヌーンティー男子会参加権', '開催：8月9日(日) 14時〜（70分間）', '場所：都内近郊予定', '集合チェキ（サインなし）込み・食事代込み'],
          delivery: ['※ 男性の方限定のプランです', '※ 当日は性別が確認できる身分証明書をご持参ください', '※ 会場までの交通費はご負担いただきます'],
        },
        {
          id: 'taiken_photo_kano',
          price: '30,000',
          limit: '5人限定',
          image: 'taiken-photo-kano.jpg',
          title: 'きゃのちと！はじめての撮影会',
          description: '5/25(月) 21時〜販売開始',
          subItems: [],
          items: ['個別撮影会参加権（1枠50分・完全入替制）', '開催：9月13日(日) 午後〜', '場所：都内スタジオ予定', 'スマホ撮影・三脚使用の一眼レフ撮影可（動画撮影不可）', 'SNS掲載自由'],
          delivery: ['※ 1メンバーにつきお1人様1枠のみ購入可', '※ 接触行為・過度なポーズ指定・公序良俗に反する撮影は禁止', '※ 会場までの交通費はご負担いただきます'],
        },
        {
          id: 'taiken_photo_sari',
          price: '30,000',
          limit: '5人限定',
          image: 'taiken-photo-sari.jpg',
          title: 'さりちゃんと！はじめての撮影会',
          description: '5/25(月) 21時〜販売開始',
          subItems: [],
          items: ['個別撮影会参加権（1枠50分・完全入替制）', '開催：9月13日(日) 午後〜', '場所：都内スタジオ予定', 'スマホ撮影・三脚使用の一眼レフ撮影可（動画撮影不可）', 'SNS掲載自由'],
          delivery: ['※ 1メンバーにつきお1人様1枠のみ購入可', '※ 接触行為・過度なポーズ指定・公序良俗に反する撮影は禁止', '※ 会場までの交通費はご負担いただきます'],
        },
        {
          id: 'taiken_photo_reina',
          price: '30,000',
          limit: '5人限定',
          image: 'taiken-photo-reina.jpg',
          title: 'れーにゃと！はじめての撮影会',
          description: '5/25(月) 21時〜販売開始',
          subItems: [],
          items: ['個別撮影会参加権（1枠50分・完全入替制）', '開催：9月13日(日) 午後〜', '場所：都内スタジオ予定', 'スマホ撮影・三脚使用の一眼レフ撮影可（動画撮影不可）', 'SNS掲載自由'],
          delivery: ['※ 1メンバーにつきお1人様1枠のみ購入可', '※ 接触行為・過度なポーズ指定・公序良俗に反する撮影は禁止', '※ 会場までの交通費はご負担いただきます'],
        },
        {
          id: 'taiken_photo_haru',
          price: '30,000',
          limit: '5人限定',
          image: 'taiken-photo-haru.jpg',
          title: 'ねむちゃんと！はじめての撮影会',
          description: '5/25(月) 21時〜販売開始',
          subItems: [],
          items: ['個別撮影会参加権（1枠50分・完全入替制）', '開催：9月13日(日) 午後〜', '場所：都内スタジオ予定', 'スマホ撮影・三脚使用の一眼レフ撮影可（動画撮影不可）', 'SNS掲載自由'],
          delivery: ['※ 1メンバーにつきお1人様1枠のみ購入可', '※ 接触行為・過度なポーズ指定・公序良俗に反する撮影は禁止', '※ 会場までの交通費はご負担いただきます'],
        },
        {
          id: 'taiken_photo_yuka',
          price: '30,000',
          limit: '5人限定',
          image: 'taiken-photo-yuka.jpg',
          title: 'ぺんざむと！はじめての撮影会',
          description: '5/25(月) 21時〜販売開始',
          subItems: [],
          items: ['個別撮影会参加権（1枠50分・完全入替制）', '開催：9月13日(日) 午後〜', '場所：都内スタジオ予定', 'スマホ撮影・三脚使用の一眼レフ撮影可（動画撮影不可）', 'SNS掲載自由'],
          delivery: ['※ 1メンバーにつきお1人様1枠のみ購入可', '※ 接触行為・過度なポーズ指定・公序良俗に反する撮影は禁止', '※ 会場までの交通費はご負担いただきます'],
        },
        {
          id: 'taiken_off_kano',
          price: '50,000',
          limit: '15人限定',
          image: 'taiken-off-kano.jpg',
          title: 'きゃのちと！オフイベ参加権',
          description: '6/1(月) 21時〜販売開始',
          subItems: [],
          items: ['個別お礼メッセージ動画', '直筆お手紙', 'イベント参加権', '開催：7月11日(土) 15時〜（2時間）', '場所：都内近郊予定', '施設利用料込み'],
          delivery: ['メッセージ動画はご登録のメールアドレスへ', 'お手紙はご登録の住所へ', '宛名と読み仮名を購入時アンケートにご記入ください', '※ 会場までの交通費はご負担いただきます', '※ 購入後のキャンセルは不可'],
        },
        {
          id: 'taiken_off_sari',
          price: '50,000',
          limit: '15人限定',
          image: 'taiken-off-sari.jpg',
          title: 'さりちゃんと！オフイベ参加権',
          description: '6/1(月) 21時〜販売開始',
          subItems: [],
          items: ['個別お礼メッセージ動画', '直筆お手紙', 'イベント参加権', '開催：7月12日(日) 15時〜（2時間）', '場所：都内近郊予定', '施設利用料込み'],
          delivery: ['メッセージ動画はご登録のメールアドレスへ', 'お手紙はご登録の住所へ', '宛名と読み仮名を購入時アンケートにご記入ください', '※ 会場までの交通費はご負担いただきます', '※ 購入後のキャンセルは不可'],
        },
        {
          id: 'taiken_off_reina',
          price: '50,000',
          limit: '15人限定',
          image: 'taiken-off-reina.jpg',
          title: 'れーにゃと！オフイベ参加権',
          description: '6/1(月) 21時〜販売開始',
          subItems: [],
          items: ['個別お礼メッセージ動画', '直筆お手紙', 'イベント参加権', '開催：7月12日(日) 19時〜（2時間）', '場所：都内近郊予定', '施設利用料込み'],
          delivery: ['メッセージ動画はご登録のメールアドレスへ', 'お手紙はご登録の住所へ', '宛名と読み仮名を購入時アンケートにご記入ください', '※ 会場までの交通費はご負担いただきます', '※ 購入後のキャンセルは不可'],
        },
        {
          id: 'taiken_off_haru',
          price: '50,000',
          limit: '15人限定',
          image: 'taiken-off-haru.jpg',
          title: 'ねむちゃんと！オフイベ参加権',
          description: '6/1(月) 21時〜販売開始',
          subItems: [],
          items: ['個別お礼メッセージ動画', '直筆お手紙', 'イベント参加権', '開催：7月11日(土) 11時〜（2時間）', '場所：都内近郊予定', '施設利用料込み'],
          delivery: ['メッセージ動画はご登録のメールアドレスへ', 'お手紙はご登録の住所へ', '宛名と読み仮名を購入時アンケートにご記入ください', '※ 飲酒は20歳以上の方のみ / 当日年齢確認あり', '※ 会場までの交通費はご負担いただきます', '※ 購入後のキャンセルは不可'],
        },
        {
          id: 'taiken_off_yuka',
          price: '50,000',
          limit: '15人限定',
          image: 'taiken-off-yuka.jpg',
          title: 'ぺんざむと！オフイベ参加権',
          description: '6/1(月) 21時〜販売開始',
          subItems: [],
          items: ['個別お礼メッセージ動画', '直筆お手紙', 'イベント参加権', '開催：7月12日(日) 11時〜（2時間）', '場所：都内近郊予定', '施設利用料込み'],
          delivery: ['メッセージ動画はご登録のメールアドレスへ', 'お手紙はご登録の住所へ', '宛名と読み仮名を購入時アンケートにご記入ください', '※ 食物アレルギーをお持ちの方は購入前にお問い合わせください', '※ 会場までの交通費はご負担いただきます', '※ 購入後のキャンセルは不可'],
        },
      ],
    },
    {
      id: 'creative',
      tabLabel: 'クリエイティブ',
      headerType: 'normal',
      title: 'クリエイティブプラン',
      periodText: '',
      periodNote: '',
      visible: true,
      comingSoon: false,
      notices: [],
      cards: [
        {
          id: 'creative_intro30',
          price: '30,000',
          limit: '10枠限定',
          image: 'creative-intro-song.jpg',
          title: 'ゆめのせいの！自己紹介ソング制作屋さん',
          description: '5/27(水) 21時〜販売開始｜メンバー全員があなたのためにオリジナル自己紹介ソングを制作。楽曲アレンジは阿部 陸人が担当。',
          subItems: [],
          items: [],
          delivery: ['※ 著作権・著作隣接権はyoumenosayに帰属します'],
        },
        {
          id: 'creative_song200',
          price: '200,000',
          limit: '3枠限定',
          image: 'creative-song-kano.jpg',
          title: 'きゃのちの！楽曲制作屋さん',
          description: '5/27(水) 21時〜販売開始｜北郷可恩がオリジナルソングを作詞作曲します（5分以内）。',
          subItems: [],
          items: [],
          delivery: ['※ 著作権・著作隣接権はyoumenosayに帰属します'],
        },
        {
          id: 'creative_design30',
          price: '30,000',
          limit: '5枠限定',
          image: 'creative-design-sari.jpg',
          title: 'さりちゃんの！デザイン屋さん',
          description: '5/27(水) 21時〜販売開始｜雪乃さりがオリジナルデザインのアートワークを制作。ロゴ・フライヤー・グッズデザイン等に対応。',
          subItems: [],
          items: [],
          delivery: ['※ 著作権・著作隣接権はyoumenosayに帰属します'],
        },
        {
          id: 'creative_craft30',
          price: '30,000',
          limit: '5枠限定',
          image: 'creative-craft-reina.jpg',
          title: 'れーにゃの！小物制作屋さん',
          description: '5/27(水) 21時〜販売開始｜雨宮れいながオリジナル小物を制作。ヘアアクセ・推し活グッズ等に対応。',
          subItems: [],
          items: [],
          delivery: ['※ 著作権・著作隣接権はyoumenosayに帰属します'],
        },
        {
          id: 'creative_video30',
          price: '30,000',
          limit: '5枠限定',
          image: 'creative-video-haru.jpg',
          title: 'ねむちゃんの！動画制作屋さん',
          description: '5/27(水) 21時〜販売開始｜ねむいのはるがオリジナルリクエスト動画を制作。購入後にヒアリングあり。',
          subItems: [],
          items: [],
          delivery: ['※ 著作権・著作隣接権はyoumenosayに帰属します'],
        },
        {
          id: 'creative_yt30',
          price: '30,000',
          limit: '5枠限定',
          image: 'creative-youtube-yuka.jpg',
          title: 'ぺんざむの！YouTuber屋さん',
          description: '5/27(水) 21時〜販売開始｜陽葵優叶がオリジナルのYouTube動画を制作。個人チャンネルにアップロードされます。',
          subItems: [],
          items: [],
          delivery: ['※ 著作権・著作隣接権はyoumenosayに帰属します'],
        },
      ],
    },
    {
      id: 'special',
      tabLabel: 'スペシャル',
      headerType: 'normal',
      title: 'スペシャルプラン',
      periodText: '',
      periodNote: '',
      visible: true,
      comingSoon: false,
      notices: [],
      cards: [
        {
          id: 'special_support300',
          price: '300,000',
          limit: '1枠限定',
          image: 'special-support.jpg',
          title: 'ゆめのせいサポートメンバープラン',
          description: '6/10(水) 21時〜販売開始',
          subItems: [],
          items: ['ライブ出演権', 'リハーサル体験', '特典会サポート体験', '反省会参加権'],
          delivery: ['youmenosayの活動を実際に体験いただくプランです。', '※ コンビニ支払い不可 / 購入後のキャンセルは不可'],
        },
      ],
    },
    {
      id: 'hojin',
      tabLabel: '法人プラン',
      headerType: 'normal',
      title: '法人プラン',
      periodText: '法人・個人事業主様対象 ／ 5/25(月) 21時〜販売開始',
      periodNote: '',
      visible: true,
      comingSoon: false,
      notices: [
        '※ 各プランの購入後、担当者よりご連絡いたします',
        '※ 企業名を購入時アンケートにご記入ください',
      ],
      cards: [
        {
          id: 'hojin_ume200',
          price: '200,000',
          limit: '10枠限定',
          image: 'hojin-ume.jpg',
          title: 'ご協賛 〈梅〉',
          description: '',
          subItems: [],
          items: ['アニメーションMVエンドロールへの企業ロゴ掲載'],
          delivery: ['購入後、ロゴデータ（AI・PNG等）をご提出いただきます'],
        },
        {
          id: 'hojin_take500',
          price: '500,000',
          limit: '5枠限定',
          image: 'hojin-take.jpg',
          title: 'ご協賛 〈竹〉',
          description: '',
          subItems: [],
          items: ['アニメーションMVエンドロールへの企業ロゴ掲載', 'youmenosay公式SNSでのプロモーション権'],
          delivery: ['購入後、ロゴデータ＋プロモーション内容のヒアリングシートをお送りします'],
        },
        {
          id: 'hojin_matsu1000',
          price: '1,000,000',
          limit: '3枠限定',
          image: 'hojin-matsu.jpg',
          title: 'ご協賛 〈松〉',
          description: '',
          subItems: [],
          items: ['アニメーションMVエンドロールへの企業ロゴ掲載', 'youmenosay公式SNSでのプロモーション権', 'ライブ衣装への企業ロゴ掲載（期間限定）'],
          delivery: ['購入後、ロゴデータ・プロモーション・衣装掲載仕様のヒアリングシートをお送りします'],
        },
      ],
    },
  ],

  // コンテンツブロック（管理画面から追加・削除・並べ替え可）
  // position: about-top/bottom, project-top/bottom, milestone-top/bottom, rewards-top/bottom
  // type: image-left, image-right, image-top, image-only, text-only
  contentBlocks: [],

  // メンバーごとのプロフィール（管理画面で編集可）
  memberProfiles: {
    kano: {
      fullName: '北郷可恩', nickname: 'きゃのち', color: '#28a064',
      birthday: '5月29日', height: '160cm', bloodType: 'B型', birthplace: '',
      description: 'マルチな経験を活かし、作詞作曲、ライブ演出、全てにおいての総合プロデュースを担当。\nツインテールと圧倒的なアイドルパフォーマンスがトレードマーク。',
      skills: '',
      twitter: 'https://x.com/Dreamy_Canon', tiktok: 'https://www.tiktok.com/@dreamy_canon',
      instagram: 'https://www.instagram.com/dreamy_canon/', youtube: 'https://www.youtube.com/channel/UCZbuN4J_LPyt58bqFxde-gg',
    },
    sari: {
      fullName: '雪乃さり', nickname: 'さりちゃん', color: '#ff5dae',
      birthday: '8月7日', height: '155cm', bloodType: '？型', birthplace: '',
      description: '激あまボイスがチャームポイント。ゆめのせいに居座る天才ネコチャン。猫にしては天才。デザインも手がける。\nマイペースでふわふわしているが、突飛な言動や天然っぽくもその人の心を掴んで離さない。',
      skills: 'スノーブルー',
      twitter: 'https://x.com/sarikin_0', tiktok: 'https://www.tiktok.com/@yukin0sar1',
      instagram: 'https://www.instagram.com/yukino_sari/', youtube: '',
    },
    reina: {
      fullName: '雨宮れいな', nickname: 'れーにゃ', color: '#c840f0',
      birthday: '1月5日', height: '161cm', bloodType: 'O型', birthplace: '',
      description: '魔界から舞い降りた歌姫。\n厨二病的なものが大好きで、いつか人間界を征服したいと目論んでいる。負けず嫌いで常に完璧を目指しているが、涙脆い一面も…？',
      skills: 'Guilty+Purple',
      twitter: 'https://x.com/reina_amamiya', tiktok: 'https://www.tiktok.com/@reina_amamiya',
      instagram: 'https://www.instagram.com/amamiya_reina', youtube: 'https://www.youtube.com/channel/UCNzZGRgaAPoBbhI9kIQaHSQ',
    },
    haru: {
      fullName: 'ねむいのはる', nickname: 'ねむちゃん', color: '#4aa0e8',
      birthday: '5月3日', height: '161cm', bloodType: 'A型', birthplace: '',
      description: 'むにゃむにゃな空気と絶妙なワードセンスでオタクを虜にする癒し系。\n時にメンバーを陰から支えるしごできメガネアイドル。',
      skills: 'ハッピー陰キャグリーン',
      twitter: 'https://x.com/haru_zzz_oo', tiktok: 'https://www.tiktok.com/@hayumuchi_______',
      instagram: 'https://www.instagram.com/haru_zzz_oo', youtube: 'https://www.youtube.com/channel/UCLIzpCX0x-9pWTCgysoEJaw',
    },
    yuka: {
      fullName: '陽葵優叶', nickname: 'ぺんざむ', color: '#ff8c00',
      birthday: '10月25日', height: '167cm', bloodType: 'A型', birthplace: '',
      description: '可能性は無限大の新人アイドル。毎日ド緊張で失敗ばかりだが、諦めない気持ちは120％！\nいつか世界中をポカポカにしたいと思っている…がギャップも無限大!?',
      skills: 'ひだまりオレンジ',
      twitter: 'https://x.com/penpen_910', tiktok: 'https://www.tiktok.com/@penzamu._.0',
      instagram: 'https://www.instagram.com/penzam._.u', youtube: 'https://www.youtube.com/@%E3%81%BA%E3%82%93%E3%81%96%E3%82%80%E3%82%89%E3%81%84',
    },
  },
};
